### ISSUE TITLE
Diverse set of categories

### ISSUE THREAD

**Issue by daniel-z-kaplan** [TheDuckAI/videorl#16]
Background:
Currently seems possible to collect a large number of urls by directly querying the youtube web API (i.e. what your browser uses to communicate to youtube, not their publicly released API which only yields at max ~20k URLs per day). This can be done in a straightforward process of finding the request that your browser makes to youtube (by using the "inspect" tool and finding the request that gets JSON back). The youtube web API uses POST requests, where it seems like just copying and pasting the request json that your browser used and the endpoint it called can allow you make the requests programmatically (even without cookies). This technique has currently been tried and works using 3 endpoints:

- "/browse" for the explore page, channels, and playlists
- "/search" for search (query can be programmatically replaced)
- "/next" for youtube recommendations (video used to generate recommendations can be programmatically replaced)

There are 2 kinds of requests, the initial request, and then a "continuation" request where the response from the initial request will contain a "continuationCommand" key which will allow one to continue a previous query (equivalent to "scrolling down" to find more videos).

Finding diverse videos:
To fulfill the goal of collecting 100M - 1B URLs, we need to collect URLs in a way that both promotes massive diversity and can also be scaled up to as big as we're looking for. We both need ideas for this as well as to see practically how this works with the oddities of web requests (the most important numbers would be how many videos could . Current ideas (and approaches can be combined too):
- Using youtube search with keywords
- Searching youtube channels with keywords to then collect their video URLs
- Iterative crawling of youtube recommendations from already collected URLs (may repeat URLs though)
- Using youtube's very specific categorization of recommendations (they only sometimes appear in the topbar ) ex. "mma", "forging", "steaks"

SPEED:
Collecting URLs from a small manually generated list of search terms (n = 35) searching for only videos and sorted by view count the code on the branch `url-collection` is able to get 30k URLs (20k unique ones) in ~15 minutes which gives an estimate of up to 2 million URLs per day per thread.  

Each search only yields ~800 results.

**Comment by mtanghu** [comment]
Notes on getting around youtube blocks: 
- possibly using a time.sleep() and restarting later (at the cost of speed)
- use IPv6 as people from video2dataset have found (can be done using code from this [stackoverflow post](https://stackoverflow.com/questions/33046733/force-requests-to-use-ipv4-ipv6))
- varying up the POST request JSON data (there are a lot of "trackingParams" where it's currently unclear what they do or how they are generated)

**Comment by mtanghu** [comment]
The youtube video recommendations seem to give a lot of diversity already (yielding a surprising amount of unique channels) as shown by #22
